version: '3.8'

services:
  db:
    image: postgis/postgis:15-3.5
    container_name: e108-postgres-prod
    restart: always
    environment:
      POSTGRES_DB: e108_db_prod
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ~/postgres/prod/data:/var/lib/postgresql/data
    networks:
      - e108-network-prod

  app:
    image: backend-app-prod
    container_name: be-app-prod
    restart: always
    # env_file:
    #   - .env
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis-prod
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - JWT_SECRET=${JWT_SECRET}
      - DB_URL=${DB_URL}
      - DB_PASSWORD=${DB_PASSWORD}
      - WEATHER_SERVICE_KEY=${WEATHER_SERVICE_KEY}
      - AIR_QUALITY_SERVICE_KEY=${AIR_QUALITY_SERVICE_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - GMS_KEY=${GMS_KEY}
      - TMAP_APP_KEY=${TMAP_APP_KEY}
    networks:
      - e108-network-prod
      - ssafy-network

  redis-prod:
    image: redis:alpine
    container_name: e108-redis-prod
    restart: always
    ports:
      - "6379:6379"
    networks:
      - e108-network-prod

networks:
  e108-network-prod:
    driver: bridge
  ssafy-network:
    external: true