spring:
  # 운영용 DB 설정 (환경변수로 주입)
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # 운영용 JPA 설정
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
