server:
  servlet:
    context-path: /api/v1

spring:
  config:
    import: optional:file:.env

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}  # 기본값 dev, 서버에서 prod로 변경

  application:
    name: be

  # 공통 JPA 설정
  jpa:
    properties:
      hibernate:
        default_batch_fetch_size: 100

# JWT 설정
jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000
